### PR TITLE
Data-model-pull request

### PR DESCRIPTION
**Pull request by Besufekad-HAZ**
## Hello 😃 Reviewer 👋🏾 

### Here is a concise list of tasks I have completed :- 

- [x] - Create a Blog App.
- [x] - Initialize my project with Git.
- [x] - Set up Postgres as the database for my project.
- [x] - Build my project schema based on the ERD diagram.
- [x] - Create and run the necessary migration files to create the required tables and columns.
- [x] - Ensure that table and column names match the ERD diagram.
- [x] - Add a photo_link column to the users table to store a link to the user's profile photo.
- [x] - Include foreign keys for the appropriate tables and columns.
- [x] - Name the column holding the foreign key to the users table author_id in the posts table.
- [x] - Add corresponding indexes to all columns that are foreign keys.

### CODE REVIEW

**Review by Olamarx — APPROVED** [review]
Hi @Besufekad-HAZ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Commit messages meaningful ✔️
- adapter uses postgres ✔️
- migration ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
> Hi @Besufekad-HAZ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  [ 68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966 ](https://camo.githubusercontent.com/a98338cee785196f99e63d5b4859ff05314578e12c0b262b9c664bbf5eb482ad/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966) [ ](https://camo.githubusercontent.com/a98338cee785196f99e63d5b4859ff05314578e12c0b262b9c664bbf5eb482ad/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966)
> 
> ## Highlights
> * Linters passed ✔️
> * Readme file professional ✔️
> * Commit messages meaningful ✔️
> * adapter uses postgres ✔️
> * migration ✔️
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
> > Hi @Besufekad-HAZ,
> > Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  [ 68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966 ](https://camo.githubusercontent.com/a98338cee785196f99e63d5b4859ff05314578e12c0b262b9c664bbf5eb482ad/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966) [ ](https://camo.githubusercontent.com/a98338cee785196f99e63d5b4859ff05314578e12c0b262b9c664bbf5eb482ad/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a3878414674716f4f555572736837572f67697068792e676966)
> > ## Highlights
> > 
> > * Linters passed ✔️
> > * Readme file professional ✔️
> > * Commit messages meaningful ✔️
> > * adapter uses postgres ✔️
> > * migration ✔️
> > 
> > ## Optional suggestions
> > _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
@Olamarx Thanks for the professional review. 🙌🏾

**Pull request merged**
