### PR TITLE
N+1 integration

### PR DESCRIPTION
**Pull request by Besufekad-HAZ**
# Hello Reviewer! 👋🏾 

- ## In this pull request, me and @brainskev  did the following things :
### Here is a concise list of tasks we have completed :-

Solved the N+1 problem when fetching all posts and their comments for a user
- Wrote integration tests using Capybara for each view in the project

## Changes Made
- N+1 Problem
- We followed the instructions in the article provided and analyzed the logs to identify the queries that were causing the issue.
- We then used ActiveRecord includes method to eager load the associated records and reduce the number of database queries.

## Integration Tests
- We wrote integration tests using Capybara to test each view in the project. We grouped the tests by page and tested the following features:

## User Index Page

- We can see the username of all other users.
- We can see the profile picture for each user.
- We can see the number of posts each user has written.
- When we click on a user, we are redirected to that user's show page.

## User Show Page

- We can see the user's profile picture.
- We can see the user's username.
- We can see the number of posts the user has written.
- We can see the user's bio.
- We can see the user's first 3 posts.
- We can see a button that lets us view all of a user's posts.
- When we click a user's post, it redirects us to that post's show page.
- When we click to see all posts, it redirects us to the user's post's index page.

## User Post Index Page

- We can see the user's profile picture.
- We can see the user's username.
- We can see the number of posts the user has written.
- We can see a post's title.
- We can see some of the post's body.
- We can see the first comments on a post.
- We can see how many comments a post has.
- We can see how many likes a post has.
- We can see a section for pagination if there are more posts than fit on the view.
- When we click on a post, it redirects us to that post's show page.

## Post Show Page

- We can see the post's title.
- We can see who wrote the post.
- We can see how many comments it has.
- We can see how many likes it has.
- We can see the post body.
- We can see the username of each commentor.
- We can see the comment each commentor left.

## Screenshots
- We Included screenshots of the app's logs before and after the N+1 problem was fixed down below.
after N+1
before N+1

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @Besufekad-HAZ, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Every member of the team contributed to the PR commits
- Repo uses a professional readme template
- `capybara` gem added to `Gemfile`
- `N+1` problem fixed
- Request tests added for `Posts` and `Users` controllers

## Required Changes ♻️
_Check the comments under the review._
- I got an error when running the tests. Please these errors
Screenshot from 2023-06-27 18-54-12


- Please the following edge cases to your tests. These tests are mandatory as the test the actual business logic (core functionalities) of the app.

#### User index page
```ruby
* Tests that asserts you can see the username of all other users.
* Tests that asserts you can see the profile picture for each user.
* Tests that asserts you can see the number of posts each user has written.
* Tests that redirects to the user's show page when you click on a user.
```
#### User show page
```ruby
* Tests that asserts you can see the user's profile picture.
* Tests that asserts you can see the user's username.
* Tests that asserts you can see the number of posts the user has written.
* Tests that asserts you can see the user's bio.
* Tests that asserts you can see the user's first 3 posts.
* Tests that asserts you can see a button that lets me view all of a user's posts.
* Tests that redirects to the post's show page when you click on a user's post.
* Tests that redirects to the user's post's index page when you click on a **see all posts**.
```
#### User post index page
```ruby
* Tests that asserts you can see the user's profile picture.
* Tests that asserts you can see the user's username.
* Tests that asserts you can see the number of posts the user has written.
* Tests that asserts you can see a post's title.
* Tests that asserts you can see some of the post's body.
* Tests that asserts you can see the first comments on a post.
* Tests that asserts you can see how many comments a post has.
* Tests that asserts you can see how many likes a post has.
* Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
* Tests that redirects to the post's show page when you click on a post.
```
### User post show page
```ruby
* Tests that asserts you can see the post's title.
* Tests that asserts you can see who wrote the post.
* Tests that asserts you can see how many comments it has.
* Tests that asserts you can see how many likes it has.
* Tests that asserts you can see the post body.
* Tests that asserts you can see the username of each commentor.
* Tests that asserts you can see the comment each commentor left.
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
@afanimartin Thanks for the professional review. I'll try to fix the issues and consider the suggestions.

However about show_spec.rb the tests are working on my side so I don't know what to fix specifically 
image
image

**Review by ichala — APPROVED** [review]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Besufekad-HAZ** [comment]
@ichala Thanks for the professional review.

**Pull request merged**
